# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='last_name',
            field=models.CharField(default='last_name', max_length=100),
        ),
        migrations.AlterField(
            model_name='runner',
            name='first_name',
            field=models.CharField(default='first_name', max_length=100),
        ),
    ]
