# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_auto_20170822_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runner',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='runner',
            name='last_name',
        ),
        migrations.AddField(
            model_name='runner',
            name='name',
            field=models.CharField(default='name', max_length=60),
        ),
        migrations.AddField(
            model_name='runner',
            name='shirt_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='M', max_length=1),
        ),
    ]
