# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_auto_20170822_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='age',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='runner',
            name='mobile',
            field=models.CharField(default='0805246996', max_length=10),
        ),
        migrations.AlterField(
            model_name='runner',
            name='shirt_size',
            field=models.CharField(choices=[('24', '24 km'), ('12', '12 km'), ('5', '5 km')], default='24', max_length=2),
        ),
    ]
