# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_auto_20170822_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='distance',
            field=models.CharField(choices=[('24', '24 km'), ('12', '12 km'), ('5', '5 km')], default='24', max_length=2),
        ),
        migrations.AlterField(
            model_name='runner',
            name='shirt_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='M', max_length=1),
        ),
    ]
