# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0007_runner_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved')], default='P', max_length=10),
        ),
    ]
