# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0008_runner_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='slip',
            field=models.ImageField(default='static/images/slip/slip1.png', upload_to='static/images/slip/'),
        ),
    ]
