# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0010_auto_20170823_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='slip',
            field=models.FileField(upload_to='slip/'),
        ),
    ]
