# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0011_auto_20170823_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='gender',
            field=models.CharField(choices=[('M', 'ชาย'), ('F', 'หญิง')], max_length=1),
        ),
        migrations.AlterField(
            model_name='runner',
            name='slip',
            field=models.FileField(upload_to='slip/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='runner',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved')], default='P', max_length=1),
        ),
    ]
