# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 05:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0012_auto_20170823_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='date_pay',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
