# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0016_auto_20170824_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='shirt_size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=1),
        ),
    ]
