# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0017_auto_20170824_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='status',
            field=models.CharField(choices=[('รอตรวจสอบ', 'Pending'), ('ลงทะเบียนสำเร็จ', 'Approved'), ('มีปัญหา', 'Problem')], default='รอตรวจสอบ', max_length=20),
        ),
    ]
