# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0018_auto_20170824_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='time_pay',
            field=models.CharField(default='12:00', max_length=5),
        ),
        migrations.AlterField(
            model_name='runner',
            name='date_pay',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='runner',
            name='shirt_size',
            field=models.CharField(choices=[('S ขนาดรอบอก 38 นิ้ว', 'S'), ('M ขนาดรอบอก 40 นิ้ว', 'M'), ('L ขนาดรอบอก 42 นิ้ว', 'L'), ('XL ขนาดรอบอก 44 นิ้ว', 'XL')], max_length=1),
        ),
    ]
