# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0020_auto_20170824_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='shirt_size',
            field=models.CharField(choices=[('S', 'S ขนาดรอบอก 38 นิ้ว'), ('M', 'M ขนาดรอบอก 40 นิ้ว'), ('L', 'L ขนาดรอบอก 42 นิ้ว'), ('XL', 'XL ขนาดรอบอก 44 นิ้ว')], max_length=1),
        ),
    ]
